version: '3.7'
networks:
  my-network:
    driver: bridge
    ipam:
     driver: default
     config:
      - subnet: 192.168.98.0/24
      
services:
  jenkins:
    image: jenkins/jenkins:latest
    container_name: docker-jenkins
    privileged: true
    user: root
    ports:
      - '8081:8080'
    volumes:
      - /home/talha/jenkins:/var/jenkins_home
      - /home/talha/devops-project:/var/jenkins_home/devops-project
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      my-network:
       aliases:
        - jenkins
        
      
  tomcat:
    container_name: doc-tomcat
    image: tomcat:latest
    privileged: true
    user: root
    volumes:
      - ~/devops-project:/usr/local/tomcat/webapps/app
    ports:
      - '8080:8080'
    networks:
      my-network:
       aliases:
        - tom
       
      
